---
name: Build base images
on:
  push:
    paths:
      - 'build/base/**'
      - .github/workflows/build-base.yaml
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: fedora33
            image_name: fedora-base:33
            dockerfile: build/base/Dockerfile.fedora33
          - name: fedora34
            image_name: fedora-base:34
            dockerfile: build/base/Dockerfile.fedora34
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Build and push ${{ matrix.name }} images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_REPO }}/${{ matrix.image_name }}
